### ISSUE TITLE
modrinth incorrect build (sources)

### ISSUE THREAD

**Issue by Texbio** [teddyxlandlee/enchlevel-langpatch#2]
You accidentally uploaded the wrong build (you used sources). So nobody can run the mod without building it themselves
https://modrinth.com/mod/enchlevel-langpatch/versions

**Comment by teddyxlandlee** [comment]
i'm gonna check it

**Comment by teddyxlandlee** [comment]
I've probably mistakenly marked the sources file as the primary file. Is it okay now?

**Comment by emielderckx** [comment]
No its still the primary

**Comment by teddyxlandlee** [comment]
> No its still the primary

Try Ctrl+F5 refresh your explorer.

I'll double-check.
