### ISSUE TITLE
incomptability

### ISSUE THREAD

**Issue by Devc2** [teddyxlandlee/enchlevel-langpatch#3]
EnchLevel-LangPatch Config III isn't compatible with the newst version of Enchantment Level Language

**Comment by teddyxlandlee** [comment]
Thanks for your feedback!

As is updated in LangPatch 2.0, sub-mod loading logic is partially modified. In this update, the Config Mod is specially loaded, making it marked incompatible with legacy Config Mod.

I'll publish the fourth generation of the Config Mod later this weekend. Sorry for your inconvenience.

Please note that the latest version LangPatch is on [Modrinth](https://modrinth.com/mod/enchlevel-langpatch), and support of the page on CurseForge will be terminated.

**Comment by teddyxlandlee** [comment]
As [LangPatch Config IV](https://www.curseforge.com/minecraft/mc-mods/enchlevel-langpatch-config2/) is released, it is now compatible with LangPatch 2.0.

If you have further question, please leave your feedback here.
