### ISSUE TITLE
Incompatible with a mod in the client

### ISSUE THREAD

**Issue by LittleChest** [teddyxlandlee/enchlevel-langpatch#4]
Full Log: `https://mclo.gs/wAGZMrG`
I don't know exactly which mod is malfunctioning 😥

**Comment by teddyxlandlee** [comment]
It is `enchlevel-langpatch`.

As is checked, vanilla code of `TranslationStorage` is changed in 1.19.4.

We will publish a fix version soon after.

**Comment by teddyxlandlee** [comment]
As `2.1.0` is released now, this issue could be marked as resolved.

If you have any problems / questions, please let me know.
